### PR TITLE
fix: fix generated file judgment rule

### PR DESCRIPTION
**Pull request by devenami**
generated file judgment rule will be uncorrect if generated file first line is copyright

### CODE REVIEW

**Comment by incu6us** [comment]
thanks for contribution!
which case should it cover?

**Comment by incu6us** [comment]
I mean, do we have a doc about generated files with copyright?
By genera logic, under copyright we can have only code which will generate something, but not a code which is going to be generated.
Also, if follow the original doc about generated files the pattern should be placed on first line of generated file
`^// Code generated .* DO NOT EDIT\.$`
https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source

**Comment by devenami** [comment]
`This line must appear before the first non-comment, non-blank text in the file.`
This text comes from [https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source](https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source)

This means that the first line of text is not necessarily `^// Code generated .* DO NOT EDIT\.$`, but also other comment information. Therefore, we cannot assume that the first line in the file must be `^// Code generated .* DO NOT EDIT\.$` to be the generated text.

In order to achieve simplicity, we only need to judge that a line in the file conforms to the "^//Code generated. * DO NOT EDIT . $" rule to consider it as the generated text.

This pr is not rigorous. I will improve it again to make it conform to the specification.

**Comment by irvinlim** [comment]
@incu6us Any chance you can release a new tag to cover this fix? Thanks!

**Pull request merged**
